// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mybad.Storage.DB;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mybad.Storage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117115021_UpdParsedMatchWardTable")]
    partial class UpdParsedMatchWardTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mybad.Storage.DB.Entities.ParsedMatchWardInfo", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PlayedAtDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MatchId", "AccountId");

                    b.HasIndex("MatchId", "AccountId");

                    b.ToTable("ParsedMatchWardInfos");
                });

            modelBuilder.Entity("Mybad.Storage.DB.Entities.WardEntity", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("PosX")
                        .HasColumnType("integer");

                    b.Property<int>("PosY")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TimeLivedSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("WasDestroyed")
                        .HasColumnType("boolean");

                    b.HasKey("MatchId", "AccountId", "PosX", "PosY");

                    b.HasIndex("AccountId");

                    b.HasIndex("MatchId");

                    b.HasIndex("MatchId", "AccountId", "PosX", "PosY");

                    b.ToTable("Wards");
                });
#pragma warning restore 612, 618
        }
    }
}
