// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mybad.Storage.DB;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mybad.Storage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251229130305_AddedPlayerInfoInParsedMatchWardInfo")]
    partial class AddedPlayerInfoInParsedMatchWardInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mybad.Storage.DB.Entities.CheckedMatchMatchupEntity", b =>
                {
                    b.Property<long>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MatchId"));

                    b.HasKey("MatchId");

                    b.ToTable("matchup_checked_matches", (string)null);
                });

            modelBuilder.Entity("Mybad.Storage.DB.Entities.HeroMatchupEntity", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<int>("OtherHeroId")
                        .HasColumnType("integer");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("HeroId", "OtherHeroId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Mybad.Storage.DB.Entities.ParsedMatchWardInfo", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRadiantPlayer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWonMatch")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PlayedAtDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MatchId", "AccountId");

                    b.HasIndex("MatchId", "AccountId");

                    b.ToTable("wards_parsed_matches", (string)null);
                });

            modelBuilder.Entity("Mybad.Storage.DB.Entities.WardEntity", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("PosX")
                        .HasColumnType("integer");

                    b.Property<int>("PosY")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TimeLivedSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("WasDestroyed")
                        .HasColumnType("boolean");

                    b.HasKey("MatchId", "AccountId", "PosX", "PosY");

                    b.HasIndex("AccountId");

                    b.HasIndex("MatchId");

                    b.HasIndex("MatchId", "AccountId", "PosX", "PosY");

                    b.ToTable("wards", (string)null);
                });

            modelBuilder.Entity("Mybad.Storage.DB.Entities.HeroMatchupAllyEntity", b =>
                {
                    b.HasBaseType("Mybad.Storage.DB.Entities.HeroMatchupEntity");

                    b.ToTable("matchup_allies", (string)null);
                });

            modelBuilder.Entity("Mybad.Storage.DB.Entities.HeroMatchupEnemyEntity", b =>
                {
                    b.HasBaseType("Mybad.Storage.DB.Entities.HeroMatchupEntity");

                    b.ToTable("matchup_enemies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
